/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressUpdateDTO
 */
export interface AddressUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    streetName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    city?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressUpdateDTO
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the AddressUpdateDTO interface.
 */
export function instanceOfAddressUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressUpdateDTOFromJSON(json: any): AddressUpdateDTO {
    return AddressUpdateDTOFromJSONTyped(json, false);
}

export function AddressUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'streetName': !exists(json, 'streetName') ? undefined : json['streetName'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function AddressUpdateDTOToJSON(value?: AddressUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'streetName': value.streetName,
        'city': value.city,
        'number': value.number,
        'phoneNumber': value.phoneNumber,
    };
}

