/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDTO } from './ProductDTO';
import {
    ProductDTOFromJSON,
    ProductDTOFromJSONTyped,
    ProductDTOToJSON,
} from './ProductDTO';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface OrderDTO
 */
export interface OrderDTO {
    /**
     * 
     * @type {ProductDTO}
     * @memberof OrderDTO
     */
    product?: ProductDTO;
    /**
     * 
     * @type {UserDTO}
     * @memberof OrderDTO
     */
    user?: UserDTO;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    id?: string;
}

/**
 * Check if a given object implements the OrderDTO interface.
 */
export function instanceOfOrderDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderDTOFromJSON(json: any): OrderDTO {
    return OrderDTOFromJSONTyped(json, false);
}

export function OrderDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : ProductDTOFromJSON(json['product']),
        'user': !exists(json, 'user') ? undefined : UserDTOFromJSON(json['user']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function OrderDTOToJSON(value?: OrderDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': ProductDTOToJSON(value.product),
        'user': UserDTOToJSON(value.user),
        'id': value.id,
    };
}

