/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ProductTagDTOPagedResponse } from './ProductTagDTOPagedResponse';
import {
    ProductTagDTOPagedResponseFromJSON,
    ProductTagDTOPagedResponseFromJSONTyped,
    ProductTagDTOPagedResponseToJSON,
} from './ProductTagDTOPagedResponse';

/**
 * 
 * @export
 * @interface ProductTagDTOPagedResponseRequestResponse
 */
export interface ProductTagDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ProductTagDTOPagedResponse}
     * @memberof ProductTagDTOPagedResponseRequestResponse
     */
    response?: ProductTagDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProductTagDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ProductTagDTOPagedResponseRequestResponse interface.
 */
export function instanceOfProductTagDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductTagDTOPagedResponseRequestResponseFromJSON(json: any): ProductTagDTOPagedResponseRequestResponse {
    return ProductTagDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ProductTagDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTagDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ProductTagDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProductTagDTOPagedResponseRequestResponseToJSON(value?: ProductTagDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ProductTagDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

