/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductTagDTO
 */
export interface ProductTagDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductTagDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductTagDTO
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductTagDTO
     */
    createdAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductTagDTO
     */
    updatedAt?: string | null;
}

/**
 * Check if a given object implements the ProductTagDTO interface.
 */
export function instanceOfProductTagDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductTagDTOFromJSON(json: any): ProductTagDTO {
    return ProductTagDTOFromJSONTyped(json, false);
}

export function ProductTagDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTagDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function ProductTagDTOToJSON(value?: ProductTagDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tag': value.tag,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

