/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductTagAddDTO
 */
export interface ProductTagAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductTagAddDTO
     */
    tag?: string | null;
}

/**
 * Check if a given object implements the ProductTagAddDTO interface.
 */
export function instanceOfProductTagAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductTagAddDTOFromJSON(json: any): ProductTagAddDTO {
    return ProductTagAddDTOFromJSONTyped(json, false);
}

export function ProductTagAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTagAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
    };
}

export function ProductTagAddDTOToJSON(value?: ProductTagAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag': value.tag,
    };
}

