/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDTO } from './ProductDTO';
import {
    ProductDTOFromJSON,
    ProductDTOFromJSONTyped,
    ProductDTOToJSON,
} from './ProductDTO';

/**
 * 
 * @export
 * @interface ProductDTOPagedResponse
 */
export interface ProductDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ProductDTO>}
     * @memberof ProductDTOPagedResponse
     */
    data?: Array<ProductDTO> | null;
}

/**
 * Check if a given object implements the ProductDTOPagedResponse interface.
 */
export function instanceOfProductDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDTOPagedResponseFromJSON(json: any): ProductDTOPagedResponse {
    return ProductDTOPagedResponseFromJSONTyped(json, false);
}

export function ProductDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ProductDTOFromJSON)),
    };
}

export function ProductDTOPagedResponseToJSON(value?: ProductDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ProductDTOToJSON)),
    };
}

