/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface ProductDTO
 */
export interface ProductDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDTO
     */
    price?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductDTO
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {UserDTO}
     * @memberof ProductDTO
     */
    user?: UserDTO;
}

/**
 * Check if a given object implements the ProductDTO interface.
 */
export function instanceOfProductDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDTOFromJSON(json: any): ProductDTO {
    return ProductDTOFromJSONTyped(json, false);
}

export function ProductDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'user': !exists(json, 'user') ? undefined : UserDTOFromJSON(json['user']),
    };
}

export function ProductDTOToJSON(value?: ProductDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'tags': value.tags,
        'user': UserDTOToJSON(value.user),
    };
}

