/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductTagDTO } from './ProductTagDTO';
import {
    ProductTagDTOFromJSON,
    ProductTagDTOFromJSONTyped,
    ProductTagDTOToJSON,
} from './ProductTagDTO';

/**
 * 
 * @export
 * @interface ProductTagDTOPagedResponse
 */
export interface ProductTagDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductTagDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductTagDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductTagDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ProductTagDTO>}
     * @memberof ProductTagDTOPagedResponse
     */
    data?: Array<ProductTagDTO> | null;
}

/**
 * Check if a given object implements the ProductTagDTOPagedResponse interface.
 */
export function instanceOfProductTagDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductTagDTOPagedResponseFromJSON(json: any): ProductTagDTOPagedResponse {
    return ProductTagDTOPagedResponseFromJSONTyped(json, false);
}

export function ProductTagDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTagDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ProductTagDTOFromJSON)),
    };
}

export function ProductTagDTOPagedResponseToJSON(value?: ProductTagDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ProductTagDTOToJSON)),
    };
}

