/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductTagAddDTO,
  ProductTagDTOPagedResponseRequestResponse,
  RequestResponse,
} from '../models';
import {
    ProductTagAddDTOFromJSON,
    ProductTagAddDTOToJSON,
    ProductTagDTOPagedResponseRequestResponseFromJSON,
    ProductTagDTOPagedResponseRequestResponseToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiProductTagAddProductTagPostRequest {
    productTagAddDTO?: ProductTagAddDTO;
}

export interface ApiProductTagDeleteProductTagIdDeleteRequest {
    id: string;
}

export interface ApiProductTagGetTagsGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class ProductTagApi extends runtime.BaseAPI {

    /**
     */
    async apiProductTagAddProductTagPostRaw(requestParameters: ApiProductTagAddProductTagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/ProductTag/AddProductTag`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductTagAddDTOToJSON(requestParameters.productTagAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiProductTagAddProductTagPost(requestParameters: ApiProductTagAddProductTagPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiProductTagAddProductTagPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProductTagDeleteProductTagIdDeleteRaw(requestParameters: ApiProductTagDeleteProductTagIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiProductTagDeleteProductTagIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/ProductTag/DeleteProductTag/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiProductTagDeleteProductTagIdDelete(requestParameters: ApiProductTagDeleteProductTagIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiProductTagDeleteProductTagIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProductTagGetTagsGetRaw(requestParameters: ApiProductTagGetTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductTagDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/ProductTag/GetTags`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductTagDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiProductTagGetTagsGet(requestParameters: ApiProductTagGetTagsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductTagDTOPagedResponseRequestResponse> {
        const response = await this.apiProductTagGetTagsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
